[package]
name = "storage-application"
version.workspace = true
edition.workspace = true

[dependencies]
storage-domain.workspace = true
storage-provider-api.workspace = true
storage-repository.workspace = true
provider-opendal.workspace = true
tokio.workspace = true
uuid.workspace = true
serde.workspace = true
tokio-util.workspace = true
sha2.workspace = true
chrono.workspace = true
serde_json.workspace = true
async-trait.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3", features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3", features = ["windows-native"] }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3", features = ["sync-secret-service"] }

[dev-dependencies]
tempfile.workspace = true
async-trait.workspace = true
